source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.3'

use_frameworks!

def sammiti_lib
    pod "SamMitiAR", :path => "../"
end

target 'Multiple Placing Example' do
    sammiti_lib
end

target 'Auto Placing Example' do
    sammiti_lib
end

target 'Image Detection Example' do
    sammiti_lib
end

